---
yconfig:
  config:
    menucallback: &menucallback !menucallback
  menu:
    admin/config/development/y:
      title: YAML configuration
      description: Configure YAML configuration
      page callback: drupal_get_form
      page arguments: [ y__config_form ]
      access arguments: [ administer site configuration ]
      << : *menucallback

  form:
    description:
      '#type': item
      '#title': !t Configure the Y Module
      '#description': !t This page is also an example of how to use the Y Module. The form callback is a Y plugin.
    y_cache_flag:
      '#type': checkbox
      '#title': !t YAML Configuration caching
      '#description': !t Turn YAML configuration caching on and off.

...